### ISSUE TITLE
Cannot install bpy using python 3.9

### ISSUE THREAD

**Issue by lastbasket** [AIBluefisher/DReg-NeRF#2]
While I was trying to install bpy, I run the script with

`conda env update --file blender_environment.yml`

Which returned:

`ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'DReg-NeRF/scripts/blender/bpy-3.4.0a0-cp310-cp310-manylinux_2_31_x86_64.whl'`

And when I tried to install with 

`pip install bpy`

It said:

`ERROR: No matching distribution found for bpy`

**Comment by AIBluefisher** [comment]
Hi, you can download the wheel and then install it. I provide it in the [link](https://drive.google.com/file/d/1ma383ZKYyv8iw-Ryh-okn_zDeY9yRRMn/view?usp=sharing).

**Comment by yejun688** [comment]
But you give download link python version is 3.10 , in install.sh file "conda create -n dreg_nerf python=3.9",it's appear error
ERROR: bpy-3.4.0a0-cp310-cp310-manylinux_2_31_x86_64.whl is not a supported wheel on this platform.
It seem to degrade python version
