### ISSUE TITLE
dataset devide

### ISSUE THREAD

**Issue by whalien-902** [AIBluefisher/DReg-NeRF#6]
Can you provide the code for training two NERFs by clustering image data sets with KMeans？

**Comment by AIBluefisher** [comment]
The code is available in the dataset loader. You can refer to [this line of code](https://github.com/AIBluefisher/DReg-NeRF/blob/cd5c01beab1e754ebd002a40df2e64ccdfe2955e/conerf/datasets/objaverse.py#L53).

**Comment by whalien-902** [comment]
thanks a lot
